name: Schedule random tweet
on:
  schedule:
    # UTC time
    - cron: '0 */3 * * *'
permissions:
  contents: read
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: |
          yarn install
    
      - name: Run tests
        run: |
          yarn build

      - name: Run
        run: |
          yarn run:random
        env:
          CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
          CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET}}
          ACCESS_TOKEN_KEY: ${{secrets.ACCESS_TOKEN_KEY}}
          ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
