name: Tweet on deploy
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  random_tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run tests
        run: |
          pnpm build

      - name: Run
        run: |
          pnpm run:update
        env:
          NODE_ENV: production
          CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
          CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET}}
          ACCESS_TOKEN_KEY: ${{secrets.ACCESS_TOKEN_KEY}}
          ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
